const products = [
    {
      name: "Emporio Armani shopper bag",
      image:'https://www.armani.com/variants/images/1647597321805681/F/w350.jpg',
      price: "300.00",
      category: "bags",
      brend:"Emporio Armani",
      categorytype:"bag",
      SKU:"ea-shopper-bag",
      color:'red',
      sizes: ["medium"],
      description:"",
      stockcount:1,
    },
    {
      name: "Emporio Armani shopper bag",
      image:"https://cdna.lystit.com/photos/italist/1e37224e/emporio-armani-Bianco-Medium-Myea-Bag-Shopper.jpeg",
      price: "300.00",
      category: "bags",
      brend:"Emporio Armani",
      categorytype:"bag",
      SKU:"ea-shopper-bag",
      color:'white',
      sizes: ["medium"],
      description:"",
      stockcount:2,
    },
    {
        name: "Bally cüzdan",
        image:"https://brandhunter.az/storage/products/bally-cuzdan-sku017-9qWKZG4OnKh03dzs.jpg",
        price: "300.00",
        category: "bag",
        brend:"Bally",
        categorytype:"wallet",
        SKU:"ea-shopper-bag",
        color: "black",
        sizes: [""],
        description:"Material - Dəri",
        stockcount:3,
    },
    {
        name: "Charles&Keith çanta",
        image:"https://brandhunter.az/storage/products/charleskeith-canta-sku015-W958uvvLenuSOhDn.png",
        price: "175.00",
        category: "bags",
        brend:"Charles&Keith",
        categorytype:"bag",
        SKU:"sku 00 3",
        color: "black",
        sizes: [""],
        description:"",
        stockcount:1,
    },
    {
        name: "Michael Kors çanta",
        image:"https://brandhunter.az/storage/products/michael-kors-canta-sku023-ny7jIqrn66L8zgfV.png",
        price: "190.00",
        category: "bags",
        brend:"Michael Kors",
        categorytype:'bag',
        SKU:"sku023",
        color:'white',
        sizes: [""],
        description:"",
        stockcount:1,
      },
      {
        name: "Gödəkcə ",
        image:
          "https://brandhunter.az/storage/products/godekce-sku%20006-fYhKJIR7TXgoMyOz.webp",
        price: "100.00",
        category: "clothes",
        brend:"U.S POLO ASSN.",
        categorytype:'jacket',
        SKU:"sku 006",
        color:'blue',
        sizes: ["M"],
        description:"",
        stockcount:0,
      },
      {
        name: "Armani Exchange saat ",
        image:"https://brandhunter.az/storage/products/armani-exchange-saat-sku018-hGjVUiFrjNpI8KVy.jpg",
        price: "300.00",
        category: "accessories",
        brend:"Armani Exchange",
        categorytype:'watch',
        SKU:"sku018",
        color:'black',
        sizes: [""],
        description:"Armani Exhange hədiyyə seti Case material Stainless steel Case Width 46.00 mm Case Thickness 11.00 mm Dial color Black Crystal Mineral Strap Material Stainless Steel Strap Color Black Strap Width 20.00 mm",
        stockcount:0,
      },
      {
        name: "Versace hədiyə seti ",
        image:"https://brandhunter.az/storage/products/versace-hediye-seti-sku021-2ZjlpzkIxgmJDseu.webp",
        price: "270.00",
        category: "perfume",
        brend:"Versace",
        categorytype:'perfume',
        SKU:"sku021",
        color:'pink',
        sizes: [""],
        description:"Versace Ladies Bright Crystal 3pc Gift Set EDT 90ml parfüm+Duş geli 100ml +Bədən losyonu 100ml + Çanta",
        stockcount:0,
      },
      {
        name: "Lancome Idole hədiyə seti",
        image:"https://brandhunter.az/storage/products/lancome-idole-hediye-seti-sku020-Hi5Ynxd3mZEVoKXI.webp",
        price: "250.00",
        category: "perfume",
        brend:"Lancome",
        categorytype:'perfume',
        SKU:"sku020",
        color:'pink',
        sizes: [""],
        description:"50 ml EDP + Bədən losyonu + Mascara Lancome Ladies Idole Gift Set Fragrances",
        stockcount:7,
      },
      {
        name: "Pinko çanta",
        image:"https://brandhunter.az/storage/products/pinko-canta-sku019-O4Qczw05BnVUKXvk.jpg",
        price: "350.00",
        category: "bags",
        brend:"Pinko",
        categorytype:'bag',
        SKU:"sku019",
        color:'red',
        sizes: [""],
        description:"Material - Dəri Uzunluq: 12,5 cm En: 21 cm Dərinlik: 5,5 cm Zəncirin uzunluğu: 114 cm",
        stockcount:1,
      },
      {
        name: "Əl çantası",
        image:"https://brandhunter.az/storage/products/el-cantasi-sku005-BJq51OXgFJe54lCa.webp",
        price: "110.00",
        category: "bags",
        brend:"U.S POLO ASSN.",
        categorytype:'crossbodybag',
        SKU:"sku005",
        color:'brown',
        sizes: [""],
        description:"Ölçüləri Uzunluğu - 21.59 cm Eni - 30.48 cm",
        stockcount:1,
      },
      {
        name: "Çanta",
        image:"https://brandhunter.az/storage/products/canta-sku%200%2007-XU14PjlFtWeenkZT.webp",
        price: "85.00",
        category: "bags",
        brend:"U.S POLO ASSN.",
        categorytype:'crossbodybag',
        SKU:"sku007",
        color:'brown',
        sizes: [""],
        description:"",
        stockcount:2,
      },

  ];
  
export default products;